name: generate-github-profile-snake-game

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: generate-snake
        uses: Platane/snk@v3
        with:
          github_user_name: getu091898
          outputs: dist/github-contribution-grid-snake.svg

      - name: show-generated-files
        run: ls -l dist
      
      - name: Push new snake file to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
